#!/usr/bin/env python2
import argparse

def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument('-t', '--trailing-only', help='Only remove trailing \
                         whitespace found at the end of a line. Note that this\
                         does not remove multiple blank spaces in a row if \
                         found.', action='store_true')
    parser.add_argument('input_file', help='Specify the filename that will be \
                         checked for unnecessary whitespace. A copy of this \
                         file will be stored as <input_file>.backup', type=str)
    return parser.parse_args()

def main():
    args = parse_arguments()

if __name__ == "__main__":
    main()
